### Variables
@url = http://localhost:3000/
@apiUrl = http://localhost:3000/api/v1





### Menu List Endpoint
GET {{apiUrl}}/menu



### Menu Item Endpoint
GET {{apiUrl}}/menu/1



### Event List Endpoint
GET {{apiUrl}}/events


### Event Item Endpoint
GET {{apiUrl}}/events/1



### Add Menu Endpoint
POST {{apiUrl}}/menu/add


{
	"id": "23",
    "type": "Baked",
	"item": "Mini Apple Pie",
    "description": "A delicious apple pie with a brown sugar twist. Perfect for and individual.",
    "cost": "$2.99",
	"image": "https://images.pexels.com/photos/5836631/pexels-photo-5836631.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
}

### Add Event Endpoint
POST {{apiUrl}}/events/add


{
    "id": "7",
    "name": "Winter Event",
    "time": "12PM - 4PM",
    "location": "Fox Valley Technical College",
    "description": "Join Us for coffee and treats to celebrate the new year!",
	"date": "January 1, 2026",
	
}

